#KubeJS Common Properties
#Sun Nov 03 07:29:02 UTC 2024
allowAsyncStreams=true
announceReload=true
creativeModeTabIcon=minecraft\:purple_dye
hideServerScriptErrors=false
ignoreCustomUniqueRecipeIds=false
matchJsonRecipes=true
packmode=
saveDevPropertiesInConfig=false
serverOnly=false
startupErrorGUI=true
startupErrorReportUrl=
